name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-check:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for outdated packages
      run: npx npm-check-updates --format group
      continue-on-error: true
      
    - name: Create issue for major updates
      uses: actions/github-script@v7
      if: failure()
      with:
        script: |
          const { execSync } = require('child_process');
          try {
            const outdated = execSync('npx npm-check-updates --format json', { encoding: 'utf8' });
            const outdatedPackages = JSON.parse(outdated);
            
            if (Object.keys(outdatedPackages).length > 0) {
              const title = `📦 Dependency Updates Available - ${new Date().toISOString().split('T')[0]}`;
              const body = `## Available Updates
              
              The following dependencies have updates available:
              
              ${Object.entries(outdatedPackages).map(([pkg, version]) => `- **${pkg}**: ${version}`).join('\n')}
              
              ### Next Steps
              - Review the updates for breaking changes
              - Update dependencies in a separate branch
              - Test thoroughly before merging
              
              *This issue was automatically generated by the dependency update workflow.*`;
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['dependencies', 'automated']
              });
            }
          } catch (error) {
            console.log('No major updates found or error occurred:', error.message);
          }
